# Generated by Django 5.2.16 on 2026-08-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_auth', '0003_employee_rejection_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AddField(
            model_name='employee',
            name='requested_role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('DISPATCH_MANAGER', 'Dispatch Manager'), ('FINANCE_MANAGER', 'Finance Manager'), ('ORDER_MANAGER', 'Order Manager'), ('MARKETING_MANAGER', 'Marketing Manager'), ('MONEY_COLLECTOR', 'Money Collector'), ('BINDING_MANAGER', 'Binding Manager'), ('PRINTING_MANAGER', 'Printing Manager')], help_text="The role a self-signup asked for. Carries no permissions — an admin reads it, then assigns `role` deliberately. Kept separate because `role` is what the permission classes gate on, so writing a stranger's own answer into it would let them pick their own privileges.", max_length=50, null=True),
        ),
    ]
