# Generated by Django 5.2.16 on 2026-09-24 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('BLOCK', 'Block'), ('UNBLOCK', 'Unblock'), ('DISPATCH', 'Dispatch'), ('RECEIVE', 'Receive')], max_length=20)),
                ('object_id', models.CharField(max_length=255)),
                ('changes', models.JSONField(default=dict, help_text='{"after": ...} on create, {"diff": {field: {"old", "new"}}} on update, {"before": ...} on delete.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='The user who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='auditlog_au_content_008cb4_idx')],
            },
        ),
    ]
