# Generated by Django 5.2.16 on 2026-08-11 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('min_stock', models.PositiveIntegerField(default=0, help_text='Low-stock threshold. If curr_stock drops below this, the book is flagged for re-order.')),
                ('low_selling', models.BooleanField(default=False, help_text='Set by the sales-analytics job; drives promotional campaigns.')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=200)),
                ('vendor_name', models.CharField(max_length=150)),
                ('gst_number', models.CharField(max_length=32, unique=True)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('max_capacity', models.PositiveIntegerField(default=0)),
                ('current_stock', models.PositiveIntegerField(default=0)),
                ('last_change_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['warehouse__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='inventory.section')),
            ],
            options={
                'ordering': ['section__warehouse__name', 'section__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BookInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('in_entry', models.PositiveIntegerField(default=0)),
                ('out_entry', models.PositiveIntegerField(default=0)),
                ('curr_stock', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_records', to='inventory.book')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_records', to='inventory.rack')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_records', to='inventory.vendor')),
            ],
            options={
                'verbose_name_plural': 'Book inventory',
                'ordering': ['book__title', 'rack__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='rack',
            constraint=models.UniqueConstraint(fields=('section', 'name'), name='uniq_rack_name_per_section'),
        ),
        migrations.AddConstraint(
            model_name='bookinventory',
            constraint=models.UniqueConstraint(fields=('book', 'rack'), name='uniq_book_per_rack'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('warehouse', 'name'), name='uniq_section_name_per_warehouse'),
        ),
    ]
