# Generated by Django 5.2.16 on 2026-08-16 17:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PLACED', 'Placed'), ('DISPATCHED', 'Dispatched'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_ordered', models.PositiveIntegerField()),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['purchase_order', 'book__title'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('IN', 'Stock in'), ('RECEIVE', 'Purchase order receipt'), ('RETURN_IN', 'Return to stock'), ('ADJUSTMENT_IN', 'Adjustment (increase)'), ('OUT', 'Stock out'), ('WRITE_OFF', 'Write off'), ('ADJUSTMENT_OUT', 'Adjustment (decrease)')], db_index=True, max_length=20)),
                ('quantity', models.PositiveIntegerField(help_text='Always positive. Direction comes from movement_type.')),
                ('balance_after', models.PositiveIntegerField(blank=True, help_text='BookInventory.curr_stock immediately after this movement, recorded under the same lock. Makes reconciliation a single comparison instead of a replay. Null only on rows backfilled as opening balances.', null=True)),
                ('reason', models.TextField(blank=True, help_text='Required for adjustments and write-offs.')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        # NOTE: the four Section capacity fields are *not* dropped here. They
        # are carried down to their racks by 0003, which then removes them —
        # dropping the columns in this migration would destroy the data before
        # there was anywhere to put it.
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='board',
            field=models.CharField(blank=True, db_index=True, help_text='e.g. "CBSE".', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='class_level',
            field=models.CharField(blank=True, db_index=True, help_text='e.g. "Class 12". Rendered as the first half of the Figma card tag.', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='books/covers/'),
        ),
        migrations.AddField(
            model_name='book',
            name='dead_stock_threshold_days',
            field=models.PositiveIntegerField(blank=True, help_text='Per-title override of settings.DEAD_STOCK_DEFAULT_DAYS. Q9: dead stock is computed on read, never stored.', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='default_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='book',
            name='default_rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_books', to='inventory.rack'),
        ),
        migrations.AddField(
            model_name='book',
            name='default_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_books', to='inventory.section'),
        ),
        migrations.AddField(
            model_name='book',
            name='default_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_books', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum retail price in INR. Null until priced; the register-book serializer requires it.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='bookinventory',
            name='last_out_at',
            field=models.DateTimeField(blank=True, help_text='When stock last left this rack. Drives dead-stock ageing; falls back to created_at for stock that never moved.', null=True),
        ),
        migrations.AddField(
            model_name='rack',
            name='current_stock',
            field=models.PositiveIntegerField(default=0, help_text='Books on this rack right now. Written only by adjust_stock().'),
        ),
        migrations.AddField(
            model_name='rack',
            name='last_change_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rack',
            name='max_capacity',
            field=models.PositiveIntegerField(default=0, help_text='How many books this rack can hold. 0 means unmeasured.'),
        ),
        migrations.AddField(
            model_name='rack',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racks_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='categories_supplied',
            field=models.JSONField(blank=True, default=list, help_text='List of category strings, e.g. ["Fiction", "Self-Help"]. The UI collects them comma-separated.'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_person',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vendor',
            name='expected_delivery_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bookinventory',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Last supplier seen for this (book, rack). Nullable because vendor is a property of a purchase, not of a shelf (finding M-7) — the authoritative attribution is on StockMovement and PurchaseOrder.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_records', to='inventory.vendor'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='is_blocked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(check=models.Q(('mrp__gte', 0), ('mrp__isnull', True), _connector='OR'), name='book_mrp_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(check=models.Q(('tax_percent__gte', 0), ('tax_percent__lte', 100)), name='book_tax_percent_in_range'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(check=models.Q(('default_discount_percent__gte', 0), ('default_discount_percent__lte', 100)), name='book_discount_percent_in_range'),
        ),
        migrations.AddConstraint(
            model_name='rack',
            constraint=models.CheckConstraint(check=models.Q(('current_stock__lte', models.F('max_capacity')), ('max_capacity', 0), _connector='OR'), name='rack_stock_within_capacity'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.vendor'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='inventory.book'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='Who performed it. SET_NULL so history survives an employee being deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.book'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='Set when the movement came from receiving a PO.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.rack'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Set on incoming stock only.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.vendor'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(check=models.Q(('quantity_ordered__gte', 1)), name='po_line_quantity_ordered_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gte', 0)), name='po_line_unit_price_not_negative'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['book', '-created_at'], name='stockmove_book_created'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['rack', '-created_at'], name='stockmove_rack_created'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', '-created_at'], name='stockmove_type_created'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 1)), name='stockmovement_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(check=models.Q(('movement_type__in', ['ADJUSTMENT_IN', 'ADJUSTMENT_OUT', 'WRITE_OFF']), ('reason', ''), _negated=True), name='stockmovement_reason_required'),
        ),
    ]
