# Generated by Django 5.2.16 on 2026-08-16 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_move_capacity_to_rack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Short identifier, e.g. "R-001". Optional; unique within its section among racks that set one.', max_length=40),
        ),
        migrations.AddField(
            model_name='rack',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='section',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Short identifier, e.g. "SEC-01". Optional; unique within its warehouse among sections that set one.', max_length=40),
        ),
        migrations.AddField(
            model_name='section',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Short operator-facing identifier, e.g. "WH-001". Optional; unique among warehouses that set one.', max_length=40),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Deactivate rather than delete: racks and ledger rows hang off this row and must not be orphaned.'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='rack',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('section', 'code'), name='uniq_rack_code_per_section_when_set'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('warehouse', 'code'), name='uniq_section_code_per_warehouse_when_set'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('code',), name='uniq_warehouse_code_when_set'),
        ),
    ]
