# Generated by Django 4.2.30 on 2026-08-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_warehouse_codes_and_active_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='unblocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
